### ISSUE TITLE
Gradle Build error with GitHub Actions

### ISSUE THREAD

**Issue by aditmodhvadia** [greenrobot/greenDAO#1037]
Getting an error for DaoSession and DaoMaster is not found when Android CI GitHub action is triggered for a project. I also added ./gradlew greendao before the build command to be sure but it still gives the error. Although it builds successfully on local.

### Android CI: 
```yml
name: Android CI

on:
  push:
    branches: [ master, release, develop ]
  pull_request:
    branches: [ master, release, develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build GreenDao Files
      run: ./gradlew greendao
    - name: Build with Gradle
      run: ./gradlew build
```

### Error:
/home/runner/work/iSolationAlert/iSolationAlert/app/src/main/java/edu/bu/metmobile/isolationalert/database/DaoHelper.java:51: error: cannot find symbol
        DaoMaster daoMaster = new DaoMaster(db);
        ^
  symbol:   class DaoMaster
  location: class DaoHelper
